description: application.yml in config-repo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true

info:
  app:
    name: ${spring.application.name}