server:
  port: 9000
eureka:
  instance:
    instanceId: ${spring.cloud.client.hostname}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    metadataMap:
      zone: hz
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
#    prefer-same-zone-eureka: true
management:
  security:
    enabled: false